### ISSUE TITLE
Section break starts new section with first system indentation.

### ISSUE THREAD

**Issue by ErlingIv** [Jojo-Schmitz/MuseScore#280]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Saving and reopening a score always resets the section break system indentation to default setting.

### Steps to reproduce

Add a section break and add a measure after the break.
Remove the system indentation flag.
Save score
Open score.
System indentation flag is set back to default.

### MuseScore Version

3.6 and 3.7

### Regression

I don't know

### Operating system

Windows 10 & 11

**Comment by Jojo-Schmitz** [comment]
Does this problem exist in Mu4 too?
If so, please report it there too, https://github.com/musescore/MuseScore/issues/new/choose

**Comment by Jojo-Schmitz** [comment]
Apparently Mu4 doesn't have that setting at all, Mu3 has it and does save it to the score:
```xml
        <LayoutBreak>
          <subtype>section</subtype>
          <firstSystemIndentation>0</firstSystemIndentation>
          </LayoutBreak>
 ```
 but apparently ignores it on read

**Comment by Jojo-Schmitz** [comment]
Gaahhhh!!! A simple typo, it writes `firstSystemIndentation` but reads `firstSystemIdentation`, which of course doesn't exist...

**Comment by Jojo-Schmitz** [comment]
See #282

**Comment by Jojo-Schmitz** [comment]
Fixed via #282

**Comment by ErlingIv** [comment]
Thanks!

**Comment by Jojo-Schmitz** [comment]
Thanks for the report, really strange that nobody noticed this since 3.6.0 got released with this feature and bug

**Comment by ErlingIv** [comment]
There is still a little "however" to this fix:
To publish a score to MuseScore.com still relies on 3.6 due to 3.7 crash during publishing.
That “ruins” the fix that 3.7 has.
However, also updating an existing score in 3.7 and publishing to MuseScore, (with the very annoying MuseScore crash) still shows the unwanted indentations on the website. Even for “fresh” scores made in 3.7.
Publishing scores from 4.2 works OK.

**Comment by Jojo-Schmitz** [comment]
I can't fix the musescore.com backend, unfortunately

**Comment by ErlingIv** [comment]
No, unfortunately not :) 
But are there any progress on the 3.7 crash when publishing problem.

**Comment by Jojo-Schmitz** [comment]
You meen #261? No, as I can't reproduce it locally under a debugger

**Comment by ErlingIv** [comment]
OK, however another indentation update: When style setting "Enable indentation of first system" is removed, the section break setting for the following indentations seem to be ignored.

**Comment by Jojo-Schmitz** [comment]
That's by design

**Comment by ErlingIv** [comment]
OK, I see. 
(Strange though to design unnecessary dependencies between independent elements.)

**Comment by Jojo-Schmitz** [comment]
The condition is:
```cpp
            lc.firstSystemIndent  = lc.firstSystem && measure->sectionBreakElement()->firstSystemIndentation() && styleB(Sid::enableIndentationOnFirstSystem);
```
